// Gerado por scripts/gen-map.ts a partir do Natural Earth 110m land. Não editar.
// Bitset 96×40 (480 bytes), índice = y·96 + x, LSB primeiro.
export const WORLD_WIDTH = 96;
export const WORLD_HEIGHT = 40;
export const WORLD = 'AADA3/8PADAAAgAAAABB5/8HEAAAGAAAAIDrC/4DAEDg/wIA8Pe+MvwB4AH1////+///MTwMuPn/////8P9/GBgA3v////93QPB/eAAAiP///z8EAOD/+wGA9P///x8EAMD//wCA/////x8AAID/fwCA/////x8AAID/HwDAadj//28AAID/DwDgtN///yMAAAD/DwBAB/z//xQAAAD+AwDgb/7//wAAAAA8BADg/9///wAAAAA4AADw/338/wAAAAAwCQDw//t4DgAAAADgAADw/zswHgEAAAAAAgDw/wcQHAAAAAAA8ADw/x8wgAIAAAAA+APg/h8AgAAAAAAA+AcA+A8ATAAAAAAA/A8A/AcAaAgAAAAA/H8A+AMAAGAAAAAA+H8A+AcAAIAAAAAA8D8A+AcAAAgAAAAA4D8A+BMAAF4AAAAA4B8A8BEAgP8AAAAA4AcA8BEAwP8BAAAA4AcA8AEAwP8BAAAA4AMA4AAAgPsBAAAA4AEAAAAAAOBAAAAAcAAAAAAAAABAAAAAYAAAAAAAAAAgAAAAMAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
